version: '3.8'

services:
  nuxt:
    image: node:18
    container_name: nuxt_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run generate"
    environment:
      - NUXT_PUBLIC_API_URL=https://mdvdback.daw.inspedralbes.cat/api
    restart: always
